compatibility_flags = [ "nodejs_compat", "global_navigator" ]

[vars]
VITE_ASSET_BASE_URL="https://assets.digitaldesa.id"
VITE_GRAPHQL_ENDPOINT="https://api-profil-v2.digitaldesa.id/grapher"
VITE_GRAPHQL_ACCESS_WEBTOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkRHRFNXVCJ9.eyJyb2wiOiJ1c2VyIiwic3ViIjoiZGlnaWRlcy5pZCIsImZsZyI6IlZFUklGSUVEIiwiZXhwIjo0NzA3Njk1Mzk4LCJ2ZXIiOiJwcm9maWxAZGlnaXRhbGRlc2EuaWQifQ.h_K3tP_9DCOVLHkZ1w-wO2nWOBrM54yTvCbQ0kgw7a4"
VITE_GOOGLE_OAUTH_CLIENT_ID="262708630123-dm8t5c0leauujuvru4okrcuhe8upvbmt.apps.googleusercontent.com"
VITE_FACEBOOK_OAUTH_CLIENT_ID=""
VITE_RECAPTCHA_SITE_KEY="6Lep520pAAAAABk2APNkzFY9wrK-buVGiaJb2tkP"
VITE_GA_ID="G-FLQYW0G73E"
VITE_MAPTILER_KEY="jspyY6xUXXKisvWc93N7"
PORT="3000"
BASE_DOMAIN="localhost"
GRAPHQL_ACCESS_WEBTOKEN=""
WEBTOKEN_SIGNING_SECRET=""
BACKOFFICE_DOMAIN="profil.digitaldesa.id"

[[kv_namespaces]]
binding="DOMAIN_MAP_KV"
id="domain_map_kv"
