export type VarsMap = {
  ["scale"]: "1"
  ["cursor-type"]: "default"
  ["webkit-font-smoothing"]: "true"
  ["color-white"]: "#fff"
  ["color-black"]: "#000"
  ["font-family"]: "Outfit"
  ["font-family-monospace"]: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace"
  ["font-family-headings"]: "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji"
  ["heading-font-weight"]: "700"
  ["radius-default"]: "sm"
  ["line-height-xs"]: "1.4"
  ["line-height-sm"]: "1.45"
  ["line-height-md"]: "1.55"
  ["line-height-lg"]: "1.6"
  ["line-height-xl"]: "1.65"
  ["font-size-xs"]: "calc(0.75rem * var(--mantine-scale))"
  ["font-size-sm"]: "calc(0.875rem * var(--mantine-scale))"
  ["font-size-md"]: "calc(1rem * var(--mantine-scale))"
  ["font-size-lg"]: "calc(1.125rem * var(--mantine-scale))"
  ["font-size-xl"]: "calc(1.25rem * var(--mantine-scale))"
  ["breakpoint-xs"]: "36em"
  ["breakpoint-sm"]: "48em"
  ["breakpoint-md"]: "62em"
  ["breakpoint-lg"]: "75em"
  ["breakpoint-xl"]: "88em"
  ["spacing-xs"]: "calc(0.625rem * var(--mantine-scale))"
  ["spacing-sm"]: "calc(0.75rem * var(--mantine-scale))"
  ["spacing-md"]: "calc(1rem * var(--mantine-scale))"
  ["spacing-lg"]: "calc(1.25rem * var(--mantine-scale))"
  ["spacing-xl"]: "calc(2rem * var(--mantine-scale))"
  ["radius-xs"]: "calc(0.125rem * var(--mantine-scale))"
  ["radius-sm"]: "calc(0.25rem * var(--mantine-scale))"
  ["radius-md"]: "calc(0.5rem * var(--mantine-scale))"
  ["radius-lg"]: "calc(1rem * var(--mantine-scale))"
  ["radius-xl"]: "calc(2rem * var(--mantine-scale))"
  ["shadow-xs"]: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), 0 calc(0.0625rem * var(--mantine-scale)) calc(0.125rem * var(--mantine-scale)) rgba(0, 0, 0, 0.1)"
  ["shadow-sm"]: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(0.625rem * var(--mantine-scale)) calc(0.9375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.4375rem * var(--mantine-scale)) calc(0.4375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale))"
  ["shadow-md"]: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(1.25rem * var(--mantine-scale)) calc(1.5625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.625rem * var(--mantine-scale)) calc(0.625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale))"
  ["shadow-lg"]: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(1.75rem * var(--mantine-scale)) calc(1.4375rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.75rem * var(--mantine-scale)) calc(0.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale))"
  ["shadow-xl"]: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(2.25rem * var(--mantine-scale)) calc(1.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(1.0625rem * var(--mantine-scale)) calc(1.0625rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale))"
  ["color-primary-filled"]: "light: #006643 | dark: #004329"
  ["color-primary-filled-hover"]: "light: #005936 | dark: #00321F"
  ["color-primary-light"]: "rgba(computed)"
  ["color-primary-light-hover"]: "rgba(computed)"
  ["color-primary-light-color"]: "light: #006643 | dark: #004329"
  ["color-primary-outline"]: "light: #006643 | dark: #004329"
  ["color-primary-outline-hover"]: "rgba(computed)"
  ["color-dark-0"]: "#C9C9C9"
  ["color-dark-1"]: "#b8b8b8"
  ["color-dark-2"]: "#828282"
  ["color-dark-3"]: "#696969"
  ["color-dark-4"]: "#424242"
  ["color-dark-5"]: "#3b3b3b"
  ["color-dark-6"]: "#2e2e2e"
  ["color-dark-7"]: "#242424"
  ["color-dark-8"]: "#1f1f1f"
  ["color-dark-9"]: "#141414"
  ["color-dark-filled"]: "light: #2e2e2e | dark: #1f1f1f"
  ["color-dark-filled-hover"]: "light: #242424 | dark: #141414"
  ["color-dark-light"]: "rgba(computed)"
  ["color-dark-light-hover"]: "rgba(computed)"
  ["color-dark-light-color"]: "light: #2e2e2e | dark: #1f1f1f"
  ["color-dark-outline"]: "light: #2e2e2e | dark: #1f1f1f"
  ["color-dark-outline-hover"]: "rgba(computed)"
  ["color-gray-0"]: "#f8f9fa"
  ["color-gray-1"]: "#f1f3f5"
  ["color-gray-2"]: "#e9ecef"
  ["color-gray-3"]: "#dee2e6"
  ["color-gray-4"]: "#ced4da"
  ["color-gray-5"]: "#adb5bd"
  ["color-gray-6"]: "#868e96"
  ["color-gray-7"]: "#495057"
  ["color-gray-8"]: "#343a40"
  ["color-gray-9"]: "#212529"
  ["color-gray-filled"]: "light: #868e96 | dark: #343a40"
  ["color-gray-filled-hover"]: "light: #495057 | dark: #212529"
  ["color-gray-light"]: "rgba(computed)"
  ["color-gray-light-hover"]: "rgba(computed)"
  ["color-gray-light-color"]: "light: #868e96 | dark: #343a40"
  ["color-gray-outline"]: "light: #868e96 | dark: #343a40"
  ["color-gray-outline-hover"]: "rgba(computed)"
  ["color-red-0"]: "#fff5f5"
  ["color-red-1"]: "#ffe3e3"
  ["color-red-2"]: "#ffc9c9"
  ["color-red-3"]: "#ffa8a8"
  ["color-red-4"]: "#ff8787"
  ["color-red-5"]: "#ff6b6b"
  ["color-red-6"]: "#fa5252"
  ["color-red-7"]: "#f03e3e"
  ["color-red-8"]: "#e03131"
  ["color-red-9"]: "#c92a2a"
  ["color-red-filled"]: "light: #fa5252 | dark: #e03131"
  ["color-red-filled-hover"]: "light: #f03e3e | dark: #c92a2a"
  ["color-red-light"]: "rgba(computed)"
  ["color-red-light-hover"]: "rgba(computed)"
  ["color-red-light-color"]: "light: #fa5252 | dark: #e03131"
  ["color-red-outline"]: "light: #fa5252 | dark: #e03131"
  ["color-red-outline-hover"]: "rgba(computed)"
  ["color-pink-0"]: "#fff0f6"
  ["color-pink-1"]: "#ffdeeb"
  ["color-pink-2"]: "#fcc2d7"
  ["color-pink-3"]: "#faa2c1"
  ["color-pink-4"]: "#f783ac"
  ["color-pink-5"]: "#f06595"
  ["color-pink-6"]: "#e64980"
  ["color-pink-7"]: "#d6336c"
  ["color-pink-8"]: "#c2255c"
  ["color-pink-9"]: "#a61e4d"
  ["color-pink-filled"]: "light: #e64980 | dark: #c2255c"
  ["color-pink-filled-hover"]: "light: #d6336c | dark: #a61e4d"
  ["color-pink-light"]: "rgba(computed)"
  ["color-pink-light-hover"]: "rgba(computed)"
  ["color-pink-light-color"]: "light: #e64980 | dark: #c2255c"
  ["color-pink-outline"]: "light: #e64980 | dark: #c2255c"
  ["color-pink-outline-hover"]: "rgba(computed)"
  ["color-grape-0"]: "#f8f0fc"
  ["color-grape-1"]: "#f3d9fa"
  ["color-grape-2"]: "#eebefa"
  ["color-grape-3"]: "#e599f7"
  ["color-grape-4"]: "#da77f2"
  ["color-grape-5"]: "#cc5de8"
  ["color-grape-6"]: "#be4bdb"
  ["color-grape-7"]: "#ae3ec9"
  ["color-grape-8"]: "#9c36b5"
  ["color-grape-9"]: "#862e9c"
  ["color-grape-filled"]: "light: #be4bdb | dark: #9c36b5"
  ["color-grape-filled-hover"]: "light: #ae3ec9 | dark: #862e9c"
  ["color-grape-light"]: "rgba(computed)"
  ["color-grape-light-hover"]: "rgba(computed)"
  ["color-grape-light-color"]: "light: #be4bdb | dark: #9c36b5"
  ["color-grape-outline"]: "light: #be4bdb | dark: #9c36b5"
  ["color-grape-outline-hover"]: "rgba(computed)"
  ["color-violet-0"]: "#f3f0ff"
  ["color-violet-1"]: "#e5dbff"
  ["color-violet-2"]: "#d0bfff"
  ["color-violet-3"]: "#b197fc"
  ["color-violet-4"]: "#9775fa"
  ["color-violet-5"]: "#845ef7"
  ["color-violet-6"]: "#7950f2"
  ["color-violet-7"]: "#7048e8"
  ["color-violet-8"]: "#6741d9"
  ["color-violet-9"]: "#5f3dc4"
  ["color-violet-filled"]: "light: #7950f2 | dark: #6741d9"
  ["color-violet-filled-hover"]: "light: #7048e8 | dark: #5f3dc4"
  ["color-violet-light"]: "rgba(computed)"
  ["color-violet-light-hover"]: "rgba(computed)"
  ["color-violet-light-color"]: "light: #7950f2 | dark: #6741d9"
  ["color-violet-outline"]: "light: #7950f2 | dark: #6741d9"
  ["color-violet-outline-hover"]: "rgba(computed)"
  ["color-indigo-0"]: "#edf2ff"
  ["color-indigo-1"]: "#dbe4ff"
  ["color-indigo-2"]: "#bac8ff"
  ["color-indigo-3"]: "#91a7ff"
  ["color-indigo-4"]: "#748ffc"
  ["color-indigo-5"]: "#5c7cfa"
  ["color-indigo-6"]: "#4c6ef5"
  ["color-indigo-7"]: "#4263eb"
  ["color-indigo-8"]: "#3b5bdb"
  ["color-indigo-9"]: "#364fc7"
  ["color-indigo-filled"]: "light: #4c6ef5 | dark: #3b5bdb"
  ["color-indigo-filled-hover"]: "light: #4263eb | dark: #364fc7"
  ["color-indigo-light"]: "rgba(computed)"
  ["color-indigo-light-hover"]: "rgba(computed)"
  ["color-indigo-light-color"]: "light: #4c6ef5 | dark: #3b5bdb"
  ["color-indigo-outline"]: "light: #4c6ef5 | dark: #3b5bdb"
  ["color-indigo-outline-hover"]: "rgba(computed)"
  ["color-blue-0"]: "#e7f5ff"
  ["color-blue-1"]: "#d0ebff"
  ["color-blue-2"]: "#a5d8ff"
  ["color-blue-3"]: "#74c0fc"
  ["color-blue-4"]: "#4dabf7"
  ["color-blue-5"]: "#339af0"
  ["color-blue-6"]: "#228be6"
  ["color-blue-7"]: "#1c7ed6"
  ["color-blue-8"]: "#1971c2"
  ["color-blue-9"]: "#1864ab"
  ["color-blue-filled"]: "light: #228be6 | dark: #1971c2"
  ["color-blue-filled-hover"]: "light: #1c7ed6 | dark: #1864ab"
  ["color-blue-light"]: "rgba(computed)"
  ["color-blue-light-hover"]: "rgba(computed)"
  ["color-blue-light-color"]: "light: #228be6 | dark: #1971c2"
  ["color-blue-outline"]: "light: #228be6 | dark: #1971c2"
  ["color-blue-outline-hover"]: "rgba(computed)"
  ["color-cyan-0"]: "#e3fafc"
  ["color-cyan-1"]: "#c5f6fa"
  ["color-cyan-2"]: "#99e9f2"
  ["color-cyan-3"]: "#66d9e8"
  ["color-cyan-4"]: "#3bc9db"
  ["color-cyan-5"]: "#22b8cf"
  ["color-cyan-6"]: "#15aabf"
  ["color-cyan-7"]: "#1098ad"
  ["color-cyan-8"]: "#0c8599"
  ["color-cyan-9"]: "#0b7285"
  ["color-cyan-filled"]: "light: #15aabf | dark: #0c8599"
  ["color-cyan-filled-hover"]: "light: #1098ad | dark: #0b7285"
  ["color-cyan-light"]: "rgba(computed)"
  ["color-cyan-light-hover"]: "rgba(computed)"
  ["color-cyan-light-color"]: "light: #15aabf | dark: #0c8599"
  ["color-cyan-outline"]: "light: #15aabf | dark: #0c8599"
  ["color-cyan-outline-hover"]: "rgba(computed)"
  ["color-teal-0"]: "#e6fcf5"
  ["color-teal-1"]: "#c3fae8"
  ["color-teal-2"]: "#96f2d7"
  ["color-teal-3"]: "#63e6be"
  ["color-teal-4"]: "#38d9a9"
  ["color-teal-5"]: "#20c997"
  ["color-teal-6"]: "#12b886"
  ["color-teal-7"]: "#0ca678"
  ["color-teal-8"]: "#099268"
  ["color-teal-9"]: "#087f5b"
  ["color-teal-filled"]: "light: #12b886 | dark: #099268"
  ["color-teal-filled-hover"]: "light: #0ca678 | dark: #087f5b"
  ["color-teal-light"]: "rgba(computed)"
  ["color-teal-light-hover"]: "rgba(computed)"
  ["color-teal-light-color"]: "light: #12b886 | dark: #099268"
  ["color-teal-outline"]: "light: #12b886 | dark: #099268"
  ["color-teal-outline-hover"]: "rgba(computed)"
  ["color-green-0"]: "#ebfbee"
  ["color-green-1"]: "#d3f9d8"
  ["color-green-2"]: "#b2f2bb"
  ["color-green-3"]: "#8ce99a"
  ["color-green-4"]: "#69db7c"
  ["color-green-5"]: "#51cf66"
  ["color-green-6"]: "#40c057"
  ["color-green-7"]: "#37b24d"
  ["color-green-8"]: "#2f9e44"
  ["color-green-9"]: "#2b8a3e"
  ["color-green-filled"]: "light: #40c057 | dark: #2f9e44"
  ["color-green-filled-hover"]: "light: #37b24d | dark: #2b8a3e"
  ["color-green-light"]: "rgba(computed)"
  ["color-green-light-hover"]: "rgba(computed)"
  ["color-green-light-color"]: "light: #40c057 | dark: #2f9e44"
  ["color-green-outline"]: "light: #40c057 | dark: #2f9e44"
  ["color-green-outline-hover"]: "rgba(computed)"
  ["color-lime-0"]: "#f4fce3"
  ["color-lime-1"]: "#e9fac8"
  ["color-lime-2"]: "#d8f5a2"
  ["color-lime-3"]: "#c0eb75"
  ["color-lime-4"]: "#a9e34b"
  ["color-lime-5"]: "#94d82d"
  ["color-lime-6"]: "#82c91e"
  ["color-lime-7"]: "#74b816"
  ["color-lime-8"]: "#66a80f"
  ["color-lime-9"]: "#5c940d"
  ["color-lime-filled"]: "light: #82c91e | dark: #66a80f"
  ["color-lime-filled-hover"]: "light: #74b816 | dark: #5c940d"
  ["color-lime-light"]: "rgba(computed)"
  ["color-lime-light-hover"]: "rgba(computed)"
  ["color-lime-light-color"]: "light: #82c91e | dark: #66a80f"
  ["color-lime-outline"]: "light: #82c91e | dark: #66a80f"
  ["color-lime-outline-hover"]: "rgba(computed)"
  ["color-yellow-0"]: "#fff9db"
  ["color-yellow-1"]: "#fff3bf"
  ["color-yellow-2"]: "#ffec99"
  ["color-yellow-3"]: "#ffe066"
  ["color-yellow-4"]: "#ffd43b"
  ["color-yellow-5"]: "#fcc419"
  ["color-yellow-6"]: "#fab005"
  ["color-yellow-7"]: "#f59f00"
  ["color-yellow-8"]: "#f08c00"
  ["color-yellow-9"]: "#e67700"
  ["color-yellow-filled"]: "light: #fab005 | dark: #f08c00"
  ["color-yellow-filled-hover"]: "light: #f59f00 | dark: #e67700"
  ["color-yellow-light"]: "rgba(computed)"
  ["color-yellow-light-hover"]: "rgba(computed)"
  ["color-yellow-light-color"]: "light: #fab005 | dark: #f08c00"
  ["color-yellow-outline"]: "light: #fab005 | dark: #f08c00"
  ["color-yellow-outline-hover"]: "rgba(computed)"
  ["color-orange-0"]: "#fff4e6"
  ["color-orange-1"]: "#ffe8cc"
  ["color-orange-2"]: "#ffd8a8"
  ["color-orange-3"]: "#ffc078"
  ["color-orange-4"]: "#ffa94d"
  ["color-orange-5"]: "#ff922b"
  ["color-orange-6"]: "#fd7e14"
  ["color-orange-7"]: "#f76707"
  ["color-orange-8"]: "#e8590c"
  ["color-orange-9"]: "#d9480f"
  ["color-orange-filled"]: "light: #fd7e14 | dark: #e8590c"
  ["color-orange-filled-hover"]: "light: #f76707 | dark: #d9480f"
  ["color-orange-light"]: "rgba(computed)"
  ["color-orange-light-hover"]: "rgba(computed)"
  ["color-orange-light-color"]: "light: #fd7e14 | dark: #e8590c"
  ["color-orange-outline"]: "light: #fd7e14 | dark: #e8590c"
  ["color-orange-outline-hover"]: "rgba(computed)"
  ["color-primary-0"]: "#B3FFEA"
  ["color-primary-1"]: "#73EDC5"
  ["color-primary-2"]: "#52C7A1"
  ["color-primary-3"]: "#4A977E"
  ["color-primary-4"]: "#298064"
  ["color-primary-5"]: "#0F7050"
  ["color-primary-6"]: "#006643"
  ["color-primary-7"]: "#005936"
  ["color-primary-8"]: "#004329"
  ["color-primary-9"]: "#00321F"
  ["color-primary-filled"]: "light: #006643 | dark: #004329"
  ["color-primary-filled-hover"]: "light: #005936 | dark: #00321F"
  ["color-primary-light"]: "rgba(computed)"
  ["color-primary-light-hover"]: "rgba(computed)"
  ["color-primary-light-color"]: "light: #006643 | dark: #004329"
  ["color-primary-outline"]: "light: #006643 | dark: #004329"
  ["color-primary-outline-hover"]: "rgba(computed)"
  ["color-secondary-0"]: "#E3FFC1"
  ["color-secondary-1"]: "#B9E581"
  ["color-secondary-2"]: "#95FD0F"
  ["color-secondary-3"]: "#77FA00"
  ["color-secondary-4"]: "#59BD00"
  ["color-secondary-5"]: "#438E00"
  ["color-secondary-6"]: "#326A00"
  ["color-secondary-7"]: "#265000"
  ["color-secondary-8"]: "#000000"
  ["color-secondary-9"]: "#000000"
  ["color-secondary-filled"]: "light: #326A00 | dark: #000000"
  ["color-secondary-filled-hover"]: "light: #265000 | dark: #000000"
  ["color-secondary-light"]: "rgba(computed)"
  ["color-secondary-light-hover"]: "rgba(computed)"
  ["color-secondary-light-color"]: "light: #326A00 | dark: #000000"
  ["color-secondary-outline"]: "light: #326A00 | dark: #000000"
  ["color-secondary-outline-hover"]: "rgba(computed)"
  ["h1-font-size"]: "calc(2.125rem * var(--mantine-scale))"
  ["h1-line-height"]: "1.3"
  ["h1-font-weight"]: "700"
  ["h2-font-size"]: "calc(1.625rem * var(--mantine-scale))"
  ["h2-line-height"]: "1.35"
  ["h2-font-weight"]: "700"
  ["h3-font-size"]: "calc(1.375rem * var(--mantine-scale))"
  ["h3-line-height"]: "1.4"
  ["h3-font-weight"]: "700"
  ["h4-font-size"]: "calc(1.125rem * var(--mantine-scale))"
  ["h4-line-height"]: "1.45"
  ["h4-font-weight"]: "700"
  ["h5-font-size"]: "calc(1rem * var(--mantine-scale))"
  ["h5-line-height"]: "1.5"
  ["h5-font-weight"]: "700"
  ["h6-font-size"]: "calc(0.875rem * var(--mantine-scale))"
  ["h6-line-height"]: "1.5"
  ["h6-font-weight"]: "700"
  ["color-bright"]: "light: #000 | dark: #fff"
  ["color-text"]: "light: #000 | dark: #C9C9C9"
  ["color-body"]: "light: #fff | dark: #1A1B1E"
  ["color-error"]: "light: #fa5252 | dark: #c92a2a"
  ["color-placeholder"]: "light: #adb5bd | dark: #5c5f66"
  ["color-anchor"]: "light: #228be6 | dark: #4dabf7"
  ["color-default"]: "light: #fff | dark: #25262b"
  ["color-default-hover"]: "light: #f8f9fa | dark: #2C2E33"
  ["color-default-color"]: "light: #000 | dark: #fff"
  ["color-default-border"]: "light: #ced4da | dark: #373A40"
  ["color-dimmed"]: "light: #868e96 | dark: #828282"
  ["color-layer-1"]: "light: var(--mantine-color-gray-0) | dark: var(--mantine-color-dark-7)"
  ["color-layer-2"]: "light: var(--mantine-color-gray-1) | dark: var(--mantine-color-dark-6)"
  ["color-layer-3"]: "light: var(--mantine-color-gray-0) | dark: var(--mantine-color-dark-7)"
  ["color-bg-main"]: "light: var(--mantine-color-white) | dark: var(--mantine-color-dark-8)"
  ["color-bg-accent"]: "light: var(--mantine-color-gray-0) | dark: var(--mantine-color-dark-7)"
  ["color-text-dark-0"]: "light: var(--mantine-color-dark-0) | dark: var(--mantine-color-gray-8)"
  ["color-text-dark-1"]: "light: var(--mantine-color-dark-1) | dark: var(--mantine-color-gray-7)"
  ["color-text-dark-2"]: "light: var(--mantine-color-dark-2) | dark: var(--mantine-color-gray-6)"
  ["color-text-dark-3"]: "light: var(--mantine-color-dark-3) | dark: var(--mantine-color-gray-5)"
  ["color-text-dark-4"]: "light: var(--mantine-color-dark-4) | dark: var(--mantine-color-gray-4)"
  ["color-text-dark-5"]: "light: var(--mantine-color-dark-5) | dark: var(--mantine-color-gray-3)"
  ["color-text-dark-6"]: "light: var(--mantine-color-dark-6) | dark: var(--mantine-color-gray-2)"
  ["color-text-dark-7"]: "light: var(--mantine-color-dark-7) | dark: var(--mantine-color-gray-1)"
  ["color-text-dark-8"]: "light: var(--mantine-color-dark-8) | dark: var(--mantine-color-gray-0)"
  ["color-text-dark-9"]: "light: var(--mantine-color-dark-9) | dark: var(--mantine-white)"
  ["color-text-green-darkest"]: "light: var(--mantine-color-green-8) | dark: var(--mantine-color-green-6)"
  ["color-text-green-darker"]: "light: var(--mantine-color-green-7) | dark: var(--mantine-color-green-5)"
  ["color-text-red-darkest"]: "light: var(--mantine-color-red-8) | dark: var(--mantine-color-red-6)"
  ["color-text-red-darker"]: "light: var(--mantine-color-red-7) | dark: var(--mantine-color-red-5)"
}

export const vars: <T extends keyof VarsMap>(key: T) => VarsMap[T]
export const breakpoints: {"xs":"36em","sm":"48em","md":"62em","lg":"75em","xl":"88em"}
export const bp: <T extends keyof typeof breakpoints>(key: T) => typeof breakpoints[T]